# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# API Gateway Routes
# Product Service route remains in properties
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/product/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=logRequest

# Order Service route is handled by RateLimitRouteConfiguration.java

# Circuit Breaker
resilience4j.circuitbreaker.instances.productService.sliding-window-size=5
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productService.permitted-number-of-calls-in-half-open-state=2

# Feign Micrometer Tracing
spring.cloud.openfeign.micrometer.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
